language: go

go:
  - 1.4
  - 1.5

install:
  - go get github.com/smartystreets/goconvey
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script: ./testall.sh
